---
  apiVersion: v1
  kind: Service
  metadata:
    name: dashboard-service
  spec:
    ports:
    - name: dasboard-service-port
      port: 80
      targetPort: dashboard-port
      protocol: TCP
    selector:
      app: dashboard
    type: NodePort